name: action

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  ikuuu_sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python3
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install requests 
          pip3 install urllib3
      - name: Run
        env:
          EMAIL_PWD: ${{ secrets.EMAIL_PWD }}
          GMAIL_SHUFFLING36_PWD_IKUUU: ${{ secrets.GMAIL_SHUFFLING36_PWD_IKUUU }}
          QQ_1615703120_PWD_IKUUU: ${{ secrets.QQ_1615703120_PWD_IKUUU }}
          QQ_3502913960_PWD_IKUUU: ${{ secrets.QQ_3502913960_PWD_IKUUU }}
        run: python3 ./ikuuu_sign.py
      - name: Show the timezone
        run: |
          echo "The run time is $TZ"
          date
      
