name: Example Workflow

on: workflow_dispatch

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use the secret
        env:
          MY_SECRET: ${{ secrets.EMAIL_PWD }}
        run: |
          echo "The secret value is: $MY_SECRET"